# Header
navbar_brand: false
menu:
  Home: index.html
  Projects: projects/
  About Daniel: about-me/
  Archives: archives/
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false

# Sidebar
widgets:
- about         # See also: `about_content`
- category
- tag
- tagcloud
- archive
- recent_posts
about_widget_content: >
  <p>A DevOp working at Unity Technologies striving to make every day
  a better one for our developers.</p>

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
favicon:
twitter_id: opdude
google_plus:
fb_admins:
fb_app_id:
